const coin=document.querySelector('#coin'),rig=document.querySelector('#coinRig'),shadow=document.querySelector('.coin-shadow'),flipBtn=document.querySelector('#flipBtn'),result=document.querySelector('#result');
const stats={total:0,heads:0,tails:0,history:[]};let choice='Cara',sound=true,flipping=false;
const $=s=>document.querySelector(s);
function tone(freq,duration,volume=.05){if(!sound)return;const ctx=new(window.AudioContext||window.webkitAudioContext)(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.value=volume;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.stop(ctx.currentTime+duration)}
function metalClink(strength=.07){if(!sound)return;const ctx=new(window.AudioContext||window.webkitAudioContext)(),master=ctx.createGain();master.gain.setValueAtTime(strength,ctx.currentTime);master.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.22);master.connect(ctx.destination);[1380,2140,3270].forEach((freq,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=i===1?'square':'triangle';o.frequency.setValueAtTime(freq,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.72,ctx.currentTime+.18);g.gain.value=[.55,.25,.16][i];o.connect(g);g.connect(master);o.start(ctx.currentTime+i*.004);o.stop(ctx.currentTime+.23)})}
function render(){$('#totalFlips').textContent=stats.total;$('#headsCount').textContent=stats.heads;$('#tailsCount').textContent=stats.tails;$('#history').innerHTML=stats.history.length?stats.history.map(x=>`<span class="item ${x==='Sello'?'tail':''}" title="${x}">${x==='Cara'?'★':'✦'}</span>`).join(''):'<span class="empty">Aún no hay lanzamientos</span>'}
function flip(power=1,gestureX=0){
 if(flipping)return;flipping=true;result.textContent='Volando…';delete coin.dataset.side;coin.classList.add('in-flight');
 const headsImg=coin.querySelector('.heads img'),tailsImg=coin.querySelector('.tails img');headsImg.src=coin.dataset.heads;tailsImg.src=coin.dataset.tails;
 const mass=Number(coin.dataset.mass||7.58),massFactor=Math.max(.7,Math.min(1.25,7.58/mass)),random=crypto.getRandomValues(new Uint32Array(4)),isHeads=random[0]%2===0,drift=Math.max(-55,Math.min(55,(random[1]%61)-30+gestureX*.12)),tilt=(random[2]%35)-17,turns=6+(random[3]%3)+Math.round(power*1.5*massFactor),height=245+Math.min(125,power*58*massFactor),duration=3000+Math.min(650,power*230/massFactor);
 coin.style.transform='rotateX(0) rotateY(0) rotateZ(0)';
 const rigAnim=rig.animate([{transform:'translate3d(0,0,0) rotateZ(0)',offset:0},{transform:`translate3d(${drift*.35}px,-${height}px,55px) rotateZ(${tilt}deg)`,offset:.40},{transform:`translate3d(${drift}px,-10px,4px) rotateZ(${tilt*.4}deg)`,offset:.78},{transform:`translate3d(${drift*.82}px,-34px,10px) rotateZ(${-tilt*.2}deg)`,offset:.86},{transform:`translate3d(${drift*.7}px,-2px,2px) rotateZ(${tilt*.12}deg)`,offset:.94},{transform:`translate3d(${drift*.68}px,0,0) rotateZ(0)`,offset:1}],{duration,easing:'cubic-bezier(.18,.58,.22,1)',fill:'forwards'});
 const edgeSpin=turns*360;
 const coinAnim=coin.animate([
  {transform:'rotateX(0deg) rotateY(0deg) rotateZ(0deg)',offset:0},
  {transform:`rotateX(80deg) rotateY(${tilt*.2}deg) rotateZ(${edgeSpin*.08}deg)`,offset:.07},
  {transform:`rotateX(87deg) rotateY(${tilt*.38}deg) rotateZ(${edgeSpin*.34}deg)`,offset:.31},
  {transform:`rotateX(83deg) rotateY(${-tilt*.32}deg) rotateZ(${edgeSpin*.76}deg)`,offset:.70},
  {transform:`rotateX(89deg) rotateY(${tilt*.18}deg) rotateZ(${edgeSpin*.88}deg)`,offset:.82},
  {transform:`rotateX(78deg) rotateY(${-tilt*.16}deg) rotateZ(${edgeSpin*.94}deg)`,offset:.91},
  {transform:`rotateX(88deg) rotateY(0deg) rotateZ(${edgeSpin}deg)`,offset:1}
 ],{duration,easing:'cubic-bezier(.2,.65,.25,1)',fill:'forwards'});
 shadow.animate([{transform:'scale(1)',opacity:.66},{transform:'scale(.32)',opacity:.14,offset:.31},{transform:'scale(.92)',opacity:.58,offset:.76},{transform:'scale(.72)',opacity:.35,offset:.84},{transform:'scale(1)',opacity:.7}],{duration,easing:'cubic-bezier(.16,.72,.2,1)'});
 tone(520,.07,.025);setTimeout(()=>metalClink(.075),duration*.76);setTimeout(()=>metalClink(.05),duration*.84);setTimeout(()=>metalClink(.032),duration*.93);
 rigAnim.onfinish=()=>{const side=isHeads?'Cara':'Sello';stats.total++;stats[isHeads?'heads':'tails']++;stats.history.unshift(side);stats.history=stats.history.slice(0,12);render();result.textContent=`${side} ${side===choice?'— acertaste':'— esta vez no'}`;rigAnim.cancel();coinAnim.cancel();headsImg.src=isHeads?coin.dataset.heads:coin.dataset.tails;headsImg.alt=`${side} de la moneda seleccionada`;coin.classList.remove('in-flight');coin.dataset.side='heads';rig.style.transform=`translate3d(${drift*.68}px,0,0)`;coin.style.transform='rotateY(0deg)';metalClink(.055);flipping=false};
}
let pointerStart=null;
coin.addEventListener('pointerdown',e=>{pointerStart={x:e.clientX,y:e.clientY,t:performance.now()};coin.setPointerCapture(e.pointerId)});
coin.addEventListener('pointerup',e=>{if(!pointerStart)return;const dy=pointerStart.y-e.clientY,dx=e.clientX-pointerStart.x,elapsed=Math.max(80,performance.now()-pointerStart.t);flip(Math.max(.7,Math.min(2.3,dy/90+350/elapsed)),dx);pointerStart=null;if(navigator.vibrate)navigator.vibrate(12)});
flipBtn.onclick=()=>flip(1.1,0);
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelector('.choice.active').classList.remove('active');b.classList.add('active');choice=b.dataset.choice;result.textContent=`Elegiste ${choice.toLowerCase()}`});
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'♬':'♩̸'};
$('#resetBtn').onclick=()=>{Object.assign(stats,{total:0,heads:0,tails:0,history:[]});render();result.textContent='Estadísticas reiniciadas'};
document.querySelectorAll('.currency').forEach(b=>b.onclick=()=>{document.querySelector('.currency.selected').classList.remove('selected');b.classList.add('selected');const d=b.dataset;coin.className=`coin ${d.currency}`;coin.dataset.mass=d.mass;coin.dataset.thickness=d.thickness;coin.dataset.heads=d.heads;coin.dataset.tails=d.tails;delete coin.dataset.side;coin.style.transform='rotateY(0deg)';const size=Math.round(128+(Number(d.diameter)-15.5)*5.5);rig.style.setProperty('--coin-size',`${Math.min(186,size)}px`);rig.style.setProperty('--edge-depth',`${Math.max(9,Math.min(13,Number(d.thickness)*6.5))}px`);coin.innerHTML=`<span class="coin-edge"></span><span class="coin-face heads"><img src="${d.heads}" alt="Cara de ${d.name}"></span><span class="coin-face tails"><img src="${d.tails}" alt="Sello de ${d.name}"></span>`;$('#currencyName').textContent=d.name;$('#specDiameter').textContent=`${String(d.diameter).replace('.',',')} mm`;$('#specMass').textContent=`${String(d.mass).replace('.',',')} g`;$('#specThickness').textContent=`${String(d.thickness).replace('.',',')} mm`;$('#specEdge').textContent=d.currency==='clp100'?'Liso/estriado':'Estriado';result.textContent=`Moneda: ${d.name}`});
