const coin=document.querySelector('#coin'),rig=document.querySelector('#coinRig'),shadow=document.querySelector('.coin-shadow'),flipBtn=document.querySelector('#flipBtn'),result=document.querySelector('#result');
const stats={total:0,heads:0,tails:0,history:[]};let choice='Cara',sound=true,flipping=false;
const $=s=>document.querySelector(s);
function tone(freq,duration,volume=.05){if(!sound)return;const ctx=new(window.AudioContext||window.webkitAudioContext)(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.value=volume;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.stop(ctx.currentTime+duration)}
function render(){$('#totalFlips').textContent=stats.total;$('#headsCount').textContent=stats.heads;$('#tailsCount').textContent=stats.tails;$('#history').innerHTML=stats.history.length?stats.history.map(x=>`<span class="item ${x==='Sello'?'tail':''}" title="${x}">${x==='Cara'?'★':'✦'}</span>`).join(''):'<span class="empty">Aún no hay lanzamientos</span>'}
function flip(){
 if(flipping)return;flipping=true;result.textContent='Volando…';
 const random=crypto.getRandomValues(new Uint32Array(4)),isHeads=random[0]%2===0,drift=(random[1]%61)-30,tilt=(random[2]%35)-17,turns=7+(random[3]%4),endY=turns*360+(isHeads?0:180);
 coin.style.transform='rotateX(0) rotateY(0) rotateZ(0)';
 const rigAnim=rig.animate([{transform:'translate3d(0,0,0) rotateZ(0)',offset:0},{transform:`translate3d(${drift*.35}px,-190px,55px) rotateZ(${tilt}deg)`,offset:.31},{transform:`translate3d(${drift}px,-10px,4px) rotateZ(${tilt*.4}deg)`,offset:.76},{transform:`translate3d(${drift*.82}px,-34px,10px) rotateZ(${-tilt*.2}deg)`,offset:.84},{transform:`translate3d(${drift*.7}px,-2px,2px) rotateZ(${tilt*.12}deg)`,offset:.93},{transform:`translate3d(${drift*.68}px,0,0) rotateZ(0)`,offset:1}],{duration:2250,easing:'cubic-bezier(.16,.72,.2,1)',fill:'forwards'});
 const coinAnim=coin.animate([{transform:'rotateX(0) rotateY(0) rotateZ(0)'},{transform:`rotateX(${turns*95}deg) rotateY(${endY*.58}deg) rotateZ(${tilt*5}deg)`,offset:.55},{transform:`rotateX(${turns*150}deg) rotateY(${endY}deg) rotateZ(${tilt}deg)`,offset:.76},{transform:`rotateX(${turns*153}deg) rotateY(${endY+22}deg) rotateZ(${-tilt*.35}deg)`,offset:.84},{transform:`rotateX(${turns*154}deg) rotateY(${endY}deg) rotateZ(${tilt*.12}deg)`,offset:1}],{duration:2250,easing:'cubic-bezier(.2,.65,.25,1)',fill:'forwards'});
 shadow.animate([{transform:'scale(1)',opacity:.66},{transform:'scale(.32)',opacity:.14,offset:.31},{transform:'scale(.92)',opacity:.58,offset:.76},{transform:'scale(.72)',opacity:.35,offset:.84},{transform:'scale(1)',opacity:.7}],{duration:2250,easing:'cubic-bezier(.16,.72,.2,1)'});
 tone(620,.09,.035);setTimeout(()=>tone(480,.07,.028),710);setTimeout(()=>tone(190,.08,.07),1710);setTimeout(()=>tone(150,.06,.04),1910);
 rigAnim.onfinish=()=>{const side=isHeads?'Cara':'Sello';stats.total++;stats[isHeads?'heads':'tails']++;stats.history.unshift(side);stats.history=stats.history.slice(0,12);render();result.textContent=`${side} ${side===choice?'— acertaste':'— esta vez no'}`;rigAnim.cancel();coinAnim.cancel();rig.style.transform=`translate3d(${drift*.68}px,0,0)`;coin.style.transform=`rotateY(${isHeads?0:180}deg)`;tone(isHeads?740:420,.14,.06);flipping=false};
}
coin.onclick=flip;flipBtn.onclick=flip;
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelector('.choice.active').classList.remove('active');b.classList.add('active');choice=b.dataset.choice;result.textContent=`Elegiste ${choice.toLowerCase()}`});
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'♬':'♩̸'};
$('#resetBtn').onclick=()=>{Object.assign(stats,{total:0,heads:0,tails:0,history:[]});render();result.textContent='Estadísticas reiniciadas'};
document.querySelectorAll('.currency').forEach(b=>b.onclick=()=>{document.querySelector('.currency.selected').classList.remove('selected');b.classList.add('selected');const d=b.dataset;coin.className=`coin ${d.currency}`;coin.innerHTML=`<span class="coin-edge"></span><span class="coin-face heads"><span class="year">${d.top}</span><b>${d.a}</b><small>${d.bottom}</small><i>${d.unit}</i></span><span class="coin-face tails"><span class="year">${d.top}</span><b>${d.b}</b><small>${d.bottom}</small><i>${d.unit}</i></span>`;$('#currencyName').textContent=d.name;$('#currencyFlag').textContent=d.flag;result.textContent=`Moneda: ${d.name}`});
