const coin=document.querySelector('#coin'), flipBtn=document.querySelector('#flipBtn'), result=document.querySelector('#result');
const stats={total:0,heads:0,tails:0,history:[]}; let choice='Cara', sound=true, flipping=false;
const $=s=>document.querySelector(s);
function tone(freq,duration,volume=.05){if(!sound)return;const ctx=new (window.AudioContext||window.webkitAudioContext)(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.value=volume;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.stop(ctx.currentTime+duration)}
function render(){ $('#totalFlips').textContent=stats.total;$('#headsCount').textContent=stats.heads;$('#tailsCount').textContent=stats.tails;$('#history').innerHTML=stats.history.length?stats.history.map(x=>`<span class="item ${x==='Sello'?'tail':''}" title="${x}">${x==='Cara'?'★':'✦'}</span>`).join(''):'<span class="empty">Aún no hay lanzamientos</span>' }
function flip(){if(flipping)return;flipping=true; result.textContent='Volando…';coin.classList.remove('spinning');void coin.offsetWidth; const isHeads=crypto.getRandomValues(new Uint32Array(1))[0]%2===0; coin.style.setProperty('--end',`${isHeads?1800:1980}deg`);coin.classList.add('spinning');tone(620,.09,.035);setTimeout(()=>tone(480,.07,.028),650);setTimeout(()=>{const side=isHeads?'Cara':'Sello';stats.total++;stats[isHeads?'heads':'tails']++;stats.history.unshift(side);stats.history=stats.history.slice(0,12);render();result.textContent=`${side} ${side===choice?'— acertaste':'— esta vez no'}`;coin.classList.remove('spinning');coin.style.transform=`rotateY(${isHeads?0:180}deg)`;tone(isHeads?740:420,.14,.06);flipping=false},1760)}
coin.onclick=flip;flipBtn.onclick=flip;
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelector('.choice.active').classList.remove('active');b.classList.add('active');choice=b.dataset.choice;result.textContent=`Elegiste ${choice.toLowerCase()}`});
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'♬':'♩̸';};$('#resetBtn').onclick=()=>{Object.assign(stats,{total:0,heads:0,tails:0,history:[]});render();result.textContent='Estadísticas reiniciadas'};
document.querySelectorAll('.currency').forEach(b=>b.onclick=()=>{document.querySelector('.currency.selected').classList.remove('selected');b.classList.add('selected');const d=b.dataset;coin.className=`coin ${d.currency}`;coin.innerHTML=`<span class="coin-face heads"><span class="year">${d.top}</span><b>${d.a}</b><small>${d.bottom}</small><i>${d.unit}</i></span><span class="coin-face tails"><span class="year">${d.top}</span><b>${d.b}</b><small>${d.bottom}</small><i>${d.unit}</i></span>`;$('#currencyName').textContent=d.name;$('#currencyFlag').textContent=d.flag;result.textContent=`Moneda: ${d.name}`});
